export const runtime = "nodejs";

import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export async function GET() {
  try {
    // Resolve path relative to the frontend folder -> ../backend/social_posts.json
    const filePath = path.join(
      process.cwd(),
      "..",
      "backend",
      "social_posts.json"
    );

    if (fs.existsSync(filePath)) {
      const raw = fs.readFileSync(filePath, "utf8");
      try {
        const posts = JSON.parse(raw);
        return NextResponse.json({ posts });
      } catch {
        // If the file exists but isn't valid JSON, return raw content
        return NextResponse.json({ posts: raw });
      }
    }

    // Fallback example payload if file is missing
    const example = [
      {
        title: "Example Post 1",
        body: "This is an example social post generated by the crew.",
      },
      {
        title: "Example Post 2",
        body: "Run the backend crew to produce `backend/social_posts.json`.",
      },
    ];

    return NextResponse.json({ posts: example });
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Failed to read posts" },
      { status: 500 }
    );
  }
}
